name: Build and push tagged release

on:
  create:
    tags:
      - v*

env:
  IMAGE_NAME: quay.io/elastx/ci-openstackclient
  IMAGE_VERSION: ${{ github.ref_name }}
  QUAY_USER: elastx+ci_openstackclient

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: elastx/actions/docker-lint@main
  build-and-push-tagged:
    runs-on:
      - self-hosted
      - non-persistent
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} .
      - name: Login to Quay
        run: docker login -u ${{ env.QUAY_USER }} -p ${{ secrets.DOCKER_PASS }} quay.io
      - name: Push the Docker image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
